os:
  - osx
  - linux
before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
  - ./utils/travis-before-script-${TRAVIS_OS_NAME}.sh
language: c
compiler:
  - gcc
  - clang
script:
  - ./utils/build-${TRAVIS_OS_NAME}.sh